### ISSUE TITLE
amp and phase needs to be on different Y axis

### ISSUE THREAD

**Issue by o-smirnov** [Mulan-94/polarvis#2]
When both amp and phase is enabled in the plot, the amp line goes flat. I think this is because the amplitude is <<1, while the phase is +/- 180. Right Y axis for phase perhaps?

**Comment by Mulan-94** [comment]
It was decided that these plots should be left as they are for now. This is because bokeh data ranges are determined by either:
- The data visible on the plot
- All the data made available to the figure at plotting

Adding an extra axis for the phase would not alleviate the issue

**Comment by o-smirnov** [comment]
Yeah agreed.
