### ISSUE TITLE
consider 3 plots?

### ISSUE THREAD

**Issue by o-smirnov** [Mulan-94/polarvis#4]
Looking at the layout now, the plots are rather "tall" -- I reckon you could easily show three with no loss of detail.

**Comment by Mulan-94** [comment]
Do you mean plots for 3 lines of sight simultaneously?

**Comment by o-smirnov** [comment]
Yes!

Also, suggest you work on your deployment, so we can have a http://cygnus.ratt-ru.org/cygnus-xyz/ URL for branch xyz.

**Comment by o-smirnov** [comment]
Looks good!
